name: Build and Deploy

on:
  push:
    branches:
      - main  # ou a branch que você estiver usando
  pull_request:
    branches:
      - main  # ou a branch que você estiver usando

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0  # ou a versão que você está usando

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # ou a versão que você está usando

    - name: Install npm packages
      run: npm install

    - name: Compile SCSS to CSS
      run: npm run build-css  # ajuste de acordo com seu script de build

    - name: Build Jekyll site
      run: bundle exec jekyll build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
